Repository berta-cms/berta, pull requests merged in 2018-12, with the labels that each got.

#220 Fix iframe in iframe loading
  editor/src/app/preview/preview.component.ts
Labels: fix

#221 Pass section without title to template
  engine/_classes/class.bertatemplate.php
  engine/js/BertaBgEditor.js
  engine/js/backend.min.js
  engine/js/maps/backend.min.js.map
Labels: fix

#224 Fix setting panel overflow
  editor/src/app/shared/animations.ts
Labels: fix

#223 Most of text input logics moved to text input service
  editor/src/app/inputs/long-text-input.component.ts
  editor/src/app/inputs/select-input.component.ts
  editor/src/app/inputs/text-input.component.ts
  editor/src/app/inputs/text-input.service.ts
  editor/src/app/sites/shared/setting.component.ts
Labels: Enhancement, fix

#226 Protect user data, stored in storage folder
  .htaccess
Labels: Enhancement, feature, fix

#225 Create entry API endpoint
  _api_app/app/Http/routes.php
  _api_app/app/Sites/Sections/Entries/SectionEntriesController.php
  _api_app/app/Sites/Sections/Entries/SectionEntriesDataService.php
  editor/src/app/preview/preview.service.ts
  editor/src/app/sites/sections/entries/entries-state/section-entries.actions.ts
  editor/src/app/sites/sections/entries/entries-state/section-entries.state.ts
  engine/js/BertaEditor.js
  engine/js/backend.min.js
  engine/js/maps/backend.min.js.map
  engine/js/maps/ng-backend.min.js.map
  engine/js/ng-backend.min.js
  engine/js/ng/shared/action-types.js
  engine/js/ng/sites/sections/entries/section-entries.actions.js
  engine/update.php
  engine/update/inc.update.createnewentry.php
Labels: Enhancement
