Repository berta-cms/berta, pull requests merged in 2019-12, with the labels that each got.

#329 $SITE_ROOT_PATH must end with a slash
  _api_app/app/Configuration/SiteSettingsConfigService.php
Labels: fix

#330 Automatically update template version in settings.xml
  _api_app/app/Sites/Settings/SiteSettingsDataService.php
Labels: fix

#331 Fix Old and New Berta setting interdependency
  _api_app/app/Configuration/SiteSettingsConfigService.php
  _api_app/app/Http/Controllers/AuthController.php
  _api_app/app/User/UserAuthServiceProvider.php
  engine/editor/inc.editor.php
  engine/editor/index.php
  engine/js/maps/ng-backend.min.js.map
  engine/js/ng-backend.min.js
  engine/js/ng/shared/utils.js
Labels: fix

#332 Fix plugin settings mixing with Site settings in the new system
  _api_app/app/Configuration/SiteSettingsConfigService.php
Labels: fix

#334 Error creating first entry on new multisite or a cloned multisite
  editor/src/app/sites/sites-state/sites.state.ts
Labels: bug

#327 Add arrow key function to text inputs
  editor/src/app/inputs/text-input.service.ts
Labels: feature

#325 Submit form when enter key is pressed
  editor/src/app/inputs/text-input.component.ts
  editor/src/app/shop/regional-costs/shop-regional-costs.component.ts
  editor/src/app/sites/shared/setting-row-add.component.ts
Labels: bug
