Repository berta-cms/berta, pull requests merged in 2019-11, with the labels that each got.

#314 Slugify tag before filtering
  _api_app/app/Sites/Sections/Entries/SectionEntriesDataService.php
Labels: critical, fix

#315 Fix gallery position
  _api_app/app/Sites/Sections/Entries/SectionEntryRenderService.php
  _api_app/app/Sites/Sections/Entries/_entryContents.twig
  engine/_classes/class.bertatemplate.php
Labels: fix

#317 Fix undefined user agent
  engine/_lib/mobile_device_detect/mobile_device_detect.php
  engine/inc.page.php
Labels: fix

#319 Fix entry ordering
  _api_app/app/Sites/Sections/Entries/SectionEntriesDataService.php
Labels: fix

#318 Gallery type Link - hover effect
  _api_app/app/Sites/Sections/Entries/Galleries/GalleryLinkRenderService.php
  _api_app/app/Sites/Sections/Entries/Galleries/galleryLink.twig
  engine/_lib/berta/default.css
  engine/css/backend.min.css
  engine/css/frontend.min.css
  engine/css/maps/backend.min.css.map
  engine/css/maps/frontend.min.css.map
  engine/js/BertaGalleryLink.js
  engine/js/backend.min.js
  engine/js/frontend.min.js
  engine/js/maps/backend.min.js.map
  engine/js/maps/frontend.min.js.map
Labels: Enhancement

#321 Fix iframe wrapper
  _templates/default/default.js
  _templates/messy-0.4.2/mess.js
  _templates/white-0.3.5/white.js
Labels: fix

#320 Fix sildeshow loop and autoplay
  _api_app/app/Sites/Sections/Entries/Galleries/GalleryPileRenderService.php
  _api_app/app/Sites/Sections/Entries/Galleries/GalleryRowRenderService.php
  _api_app/app/Sites/Sections/Entries/Galleries/GallerySlideshowRenderService.php
  _api_app/app/Sites/Sections/Entries/Galleries/gallerySlideshow.twig
  engine/js/BertaGallerySlideshow.js
  engine/js/backend.min.js
  engine/js/frontend.min.js
  engine/js/maps/backend.min.js.map
  engine/js/maps/frontend.min.js.map
Labels: fix

#304 Up lumen version from 5.2 to 5.4
  _api_app/app/Http/routes.php
  _api_app/bootstrap/app.php
  _api_app/composer.json
  _api_app/composer.lock
Labels: Enhancement

#323 Upkeep: Use version from composer.json as Berta version
  engine/inc.version.php
Labels: Enhancement

#324 Fix: responsive video, gallery items spacing
  _templates/default/maps/style.css.map
  _templates/default/scss/_responsive.scss
  _templates/default/style.css
  _templates/default/style.css.php
  _templates/mashup-0.3.5/maps/style.css.map
  _templates/mashup-0.3.5/scss/_responsive.scss
  _templates/mashup-0.3.5/style.css
  _templates/mashup-0.3.5/style.css.php
  _templates/messy-0.4.2/maps/style.css.map
  _templates/messy-0.4.2/scss/_responsive-common.scss
  _templates/messy-0.4.2/style.css
  _templates/messy-0.4.2/style.css.php
  _templates/white-0.3.5/maps/style.css.map
  _templates/white-0.3.5/scss/_responsive.scss
  _templates/white-0.3.5/style.css
  _templates/white-0.3.5/style.css.php
Labels: fix
