Repository berta-cms/berta, pull requests merged in 2019-06, with the labels that each got.

#250 Fix gallery autoplay saving
  engine/elements.php
Labels: fix

#249 File upload API
  _api_app/app/Http/Controllers/StateController.php
  _api_app/app/Http/routes.php
  _api_app/app/Providers/AppServiceProvider.php
  _api_app/app/Shared/ImageHelpers.php
  _api_app/app/Shared/Storage.php
  _api_app/app/Sites/Sections/Entries/SectionEntriesController.php
  _api_app/app/Sites/Sections/Entries/SectionEntriesDataService.php
  _api_app/app/Sites/Sections/SiteSectionsController.php
  _api_app/app/Sites/Sections/SiteSectionsDataService.php
  _api_app/app/Sites/Settings/SiteSettingsController.php
  _api_app/app/Sites/Settings/SiteSettingsDataService.php
  _api_app/app/Sites/TemplateSettings/SiteTemplateSettingsController.php
  _api_app/app/Sites/TemplateSettings/SiteTemplateSettingsDataService.php
  _api_app/bootstrap/app.php
  _api_app/config/app.php
  _api_app/resources/lang/en/validation.php
  editor/src/app/inputs/file-input.component.ts
  editor/src/app/shop/settings/shop-settings.component.ts
  editor/src/app/shop/settings/shop-settings.state.ts
  editor/src/app/sites/settings/site-settings.component.ts
  editor/src/app/sites/settings/site-settings.state.ts
  editor/src/app/sites/shared/file-upload.service.ts
  editor/src/app/sites/shared/setting.component.ts
  editor/src/app/sites/template-settings/site-template-settings.component.ts
  editor/src/app/sites/template-settings/site-template-settings.state.ts
  engine/_classes/class.bertaeditor.php
  engine/_classes/class.bertautils.php
  engine/elements.php
  engine/js/BertaGalleryEditor.js
  engine/js/BertaGalleryEditorAssets.js
  engine/js/backend.min.js
  engine/js/maps/backend.min.js.map
  engine/update.php
  engine/upload.php
Labels: Enhancement

#251 Fix video caption saving
  engine/elements.php
Labels: fix

#253 Catch saving empty settings
  _api_app/app/Sites/Settings/SiteSettingsDataService.php
  engine/_classes/class.settings.php
Labels: fix

#255 Fix 404 include
  engine/editor/inc.editor.php
  engine/error/404.php
Labels: bug

#257 Empty xml fix
  _api_app/app/Shared/Storage.php
  _api_app/app/Sites/Settings/SiteSettingsDataService.php
  _api_app/composer.json
  _api_app/tests/ExampleTest.php
  engine/_classes/class.settings.php
Labels: critical, fix

#258 Loading animation for login page
  editor/src/app/app.module.ts
  editor/src/app/login/login.component.ts
  editor/src/app/shared/loading/loading.component.ts
  editor/src/app/shared/shared.module.ts
  editor/src/app/user/user.state.ts
  editor/src/styles/_login.scss
Labels: Enhancement

#259 Error handling
  _api_app/.env.example
  _api_app/app/Exceptions/Handler.php
  _api_app/app/Http/Controllers/StateController.php
  _api_app/app/Http/routes.php
  _api_app/bootstrap/app.php
  _api_app/composer.json
  _api_app/composer.lock
  _api_app/config/sentry.php
  editor/package-lock.json
  editor/package.json
  editor/src/app/app.module.ts
  editor/src/app/sentry.error-handler.ts
Labels: Enhancement

#261 Update from Angular 7 to 8
  editor/package-lock.json
  editor/package.json
  editor/src/app/app-routing.module.ts
  editor/src/app/inputs/select-input.component.ts
  editor/src/tsconfig.app.json
  editor/tsconfig.json
Labels: Enhancement
